#!/bin/bash

set -e

[ "${ENV_NAME}" == 'development' ] \
  && [ "${XDEBUG_ENABLE}" == 'true' ] \
  && ! docker-php-ext-enable xdebug >> /dev/null 2>&1 \
  && echo "[ERROR] An error happened enabling xdebug" \
  && exit 1

envsubst < /scaffold/scaffold.ini > /usr/local/etc/php/conf.d/scaffold.ini
envsubst < /scaffold/zz-php-fpm.conf > /usr/local/etc/php-fpm.d/zz-php-fpm.conf

if [[ "$1" =~ ^(php-fpm) ]]; then exec "${@}"; else exec su-exec "${ASUSER}" "${@}"; fi
