name: Update Docker Hub repository description
on:
  push:
    branches: [main]
    paths: [README.md, .github/workflows/dockerhub-description.yml]

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: scaffoldeducation/php
          short-description: ${{ github.event.repository.description }}
